// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: GPL-3.0-only

package main

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
)

// completionShells are the shells --completion writes a script for.
var completionShells = []string{"bash", "fish", "zsh"}

// pathFlags take a file path, so the shell completes file names for them.
var pathFlags = map[string]bool{"scout": true}

// writeCompletion prints a completion script for shell, generated from the
// flag set itself, so a new flag completes without a second list to keep.
func writeCompletion(w io.Writer, fs *flag.FlagSet, shell string) error {
	type option struct{ name, usage string }
	var opts []option
	fs.VisitAll(func(f *flag.Flag) { opts = append(opts, option{f.Name, f.Usage}) })
	sort.Slice(opts, func(i, j int) bool { return opts[i].name < opts[j].name })

	var b strings.Builder
	switch shell {
	case "bash":
		var words []string
		for _, o := range opts {
			words = append(words, "--"+o.name)
		}
		fmt.Fprintf(&b, "# bash completion for scout-mcp, generated by scout-mcp --completion bash\n")
		fmt.Fprintf(&b, "_scout_mcp() {\n")
		fmt.Fprintf(&b, "  local cur=\"${COMP_WORDS[COMP_CWORD]}\" prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
		fmt.Fprintf(&b, "  case \"$prev\" in\n")
		for _, o := range opts {
			if pathFlags[o.name] {
				fmt.Fprintf(&b, "    --%s) COMPREPLY=($(compgen -f -- \"$cur\")); return ;;\n", o.name)
			}
		}
		fmt.Fprintf(&b, "    --completion) COMPREPLY=($(compgen -W %q -- \"$cur\")); return ;;\n", strings.Join(completionShells, " "))
		fmt.Fprintf(&b, "  esac\n")
		fmt.Fprintf(&b, "  COMPREPLY=($(compgen -W %q -- \"$cur\"))\n", strings.Join(words, " "))
		fmt.Fprintf(&b, "}\ncomplete -F _scout_mcp scout-mcp\n")
	case "zsh":
		fmt.Fprintf(&b, "#compdef scout-mcp\n# zsh completion for scout-mcp, generated by scout-mcp --completion zsh\n_arguments \\\n")
		for _, o := range opts {
			action := ""
			switch {
			case pathFlags[o.name]:
				action = ":path:_files"
			case o.name == "completion":
				action = ":shell:(" + strings.Join(completionShells, " ") + ")"
			case !isBool(fs, o.name):
				action = ":value: "
			}
			fmt.Fprintf(&b, "  '--%s[%s]%s' \\\n", o.name, zshEscape(o.usage), action)
		}
		fmt.Fprintf(&b, "  && return 0\n")
	case "fish":
		fmt.Fprintf(&b, "# fish completion for scout-mcp, generated by scout-mcp --completion fish\n")
		for _, o := range opts {
			extra := ""
			switch {
			case pathFlags[o.name]:
				extra = " -r -F"
			case o.name == "completion":
				extra = fmt.Sprintf(" -x -a %q", strings.Join(completionShells, " "))
			case !isBool(fs, o.name):
				extra = " -x"
			}
			fmt.Fprintf(&b, "complete -c scout-mcp -l %s -d %q%s\n", o.name, o.usage, extra)
		}
	default:
		return fmt.Errorf("--completion takes one of %s, not %q", strings.Join(completionShells, ", "), shell)
	}
	_, err := io.WriteString(w, b.String())
	return err
}

func isBool(fs *flag.FlagSet, name string) bool {
	f := fs.Lookup(name)
	if f == nil {
		return false
	}
	b, ok := f.Value.(interface{ IsBoolFlag() bool })
	return ok && b.IsBoolFlag()
}

// zshEscape makes a usage string safe inside a single-quoted _arguments spec.
func zshEscape(s string) string {
	return strings.NewReplacer("'", "'\\''", "[", "\\[", "]", "\\]", ":", "\\:").Replace(s)
}
